/**
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.serializer;

import com.dsleng.etool.xtext.presentation.view.serializer.AbstractViewDslSyntacticSequencer;

@SuppressWarnings("all")
public class ViewDslSyntacticSequencer extends AbstractViewDslSyntacticSequencer {
}
