/**
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.serializer;

import com.dsleng.etool.xtext.presentation.view.serializer.AbstractViewDslSemanticSequencer;

@SuppressWarnings("all")
public class ViewDslSemanticSequencer extends AbstractViewDslSemanticSequencer {
}
