/**
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.validation;

import com.dsleng.etool.xtext.presentation.view.validation.AbstractViewDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ViewDslValidator extends AbstractViewDslValidator {
}
