/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.view.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ViewDSLUiModule extends com.dsleng.etool.xtext.view.ui.AbstractViewDSLUiModule {
	public ViewDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
