/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ViewDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.dsleng.etool.xtext.presentation.view.ui.internal.ViewDslActivator.getInstance().getInjector("com.dsleng.etool.xtext.presentation.view.ViewDsl");
	}
	
}
