<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bobjs" nsURI="http://com/dsleng/etool/model/bobjs" nsPrefix="com.dsleng.etool.model">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrgUnit" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="langFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataManagement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spType" eType="#//BusinessType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
    <eLiterals name="Integer"/>
    <eLiterals name="String" value="1"/>
    <eLiterals name="Date" value="2"/>
    <eLiterals name="Double" value="3"/>
    <eLiterals name="Boolean" value="4"/>
    <eLiterals name="DataMap" value="5"/>
    <eLiterals name="Void" value="6" literal="void"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="References">
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessobject" eType="#//BusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Inclusion" eType="#//Inclusions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Inclusions">
    <eLiterals name="Mandatory"/>
    <eLiterals name="Optional" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="oneToone" literal="onetoone"/>
    <eLiterals name="oneTomany" value="1"/>
    <eLiterals name="manyTomany" value="2"/>
    <eLiterals name="manyToone" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObject" eSuperTypes="#//BusinessType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//References" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//BusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//Enum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedon" upperBound="-1"
        eType="#//BasedOn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOEnum" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boenum" lowerBound="1"
        eType="#//BOEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasedOn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessobject" eType="#//BusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removes" upperBound="-1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opparameters" upperBound="-1"
        eType="#//OpParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookup" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importPlugin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businesstypes" upperBound="-1"
        eType="#//BusinessType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessobjects" upperBound="-1"
        eType="#//BusinessObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boenums" upperBound="-1"
        eType="#//BOEnum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boimport" upperBound="-1"
        eType="#//BOImport" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
