<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="controls" nsURI="http://com/dsleng/etool/model/controls" nsPrefix="com.dsleng.etool.model">
  <eClassifiers xsi:type="ecore:EClass" name="ControlDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Options" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//ControlDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageinfos" upperBound="-1"
        eType="#//PageInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composites" upperBound="-1"
        eType="#//SimpleControl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageinfos" upperBound="-1"
        eType="#//PageInfo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composites" upperBound="-1"
        eType="#//Composite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueplaceholder" upperBound="-1"
        eType="#//ValuePlaceHolder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuePlaceHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeWebCtrl" eSuperTypes="#//Composite"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeMobCtrl" eSuperTypes="#//Composite"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//SimpleControl">
    <eOperations name="getCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesControl" lowerBound="1"
        eType="#//SimpleControl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
        eType="#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" upperBound="-1"
        eType="#//ValuePlaceHolder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" eType="#//ControlDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionInstance" upperBound="-1"
        eType="#//OptionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedControls" upperBound="-1"
        eType="#//SimpleControl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sibling" upperBound="-1"
        eType="#//SimpleControl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" lowerBound="1"
        eType="#//SimpleControl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
        eType="#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BOType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BOCtrl" eSuperTypes="#//Composite"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageCtrl" eSuperTypes="#//Composite"/>
</ecore:EPackage>
