<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="egov" nsURI="http://com/dsleng/etool/model/egov" nsPrefix="com.dsleng.etool.model">
  <eClassifiers xsi:type="ecore:EClass" name="EService" eSuperTypes="#//WebElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexPage" lowerBound="1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BusinessUnit" eType="ecore:EClass BOB.ecore#//OrgUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adminPages" eType="#//Admin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menu" upperBound="-1" eType="#//Menu"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//WebElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BOMaps" upperBound="-1"
        eType="#//BOMapper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagetype" eType="ecore:EClass Controls.ecore#//PageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraControls" upperBound="-1"
        eType="ecore:EClass Controls.ecore#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="North" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="South" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="West" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="East" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businesstype" eType="ecore:EClass BOB.ecore#//BusinessType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOMapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//BOAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BusinessObject" eType="ecore:EClass BOB.ecore#//BusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="botype" eType="ecore:EClass Controls.ecore#//BOType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controltype" eType="ecore:EClass Controls.ecore#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass BOB.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlparameters" upperBound="-1"
        eType="#//ControlMapper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedcontainers" upperBound="-1"
        eType="#//PreDefinedContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreDefinedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlMapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="ecore:EClass Controls.ecore#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass BOB.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreDefinedContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedvalues" upperBound="-1"
        eType="#//PreDefinedValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Admin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businesstypes" upperBound="-1"
        eType="ecore:EClass BOB.ecore#//BusinessType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menu" upperBound="-1" eType="#//Menu"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu" eSuperTypes="#//WebElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentMenu" eType="#//Menu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menuType" eType="#//MenuType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MenuType">
    <eLiterals name="Standard"/>
    <eLiterals name="TopLevel" value="1"/>
  </eClassifiers>
</ecore:EPackage>
