/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.ui.contentassist

import com.dsleng.etool.xtext.presentation.view.ui.contentassist.AbstractViewDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ViewDslProposalProvider extends AbstractViewDslProposalProvider {
}
