/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SemanticmapDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.dsleng.etool.semantic.map.ui.internal.SemanticmapDslActivator.getInstance().getInjector("com.dsleng.etool.semantic.map.SemanticmapDsl");
	}
	
}
