/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.bobjs.ui.contentassist

import com.dsleng.etool.dsl.bobjs.ui.contentassist.AbstractBObjDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BObjDslProposalProvider extends AbstractBObjDslProposalProvider {
}
