package za.co.egov.epart;
// Generated 24 Oct 2015 4:19:38 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Citizen generated by hbm2java
 */
@Entity
@Table(name="citizen"
    ,schema="public"
)
public class Citizen  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String surname;
     private String email;
     private String cell;
     private Set<Complaint> COMPLAINT_CITIZENS = new HashSet<Complaint>(0);

    public Citizen() {
    }

    public Citizen(String firstName, String surname, String email, String cell, Set<Complaint> COMPLAINT_CITIZENS) {
       this.firstName = firstName;
       this.surname = surname;
       this.email = email;
       this.cell = cell;
       this.COMPLAINT_CITIZENS = COMPLAINT_CITIZENS;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="firstname", length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="cell", length=100)
    public String getCell() {
        return this.cell;
    }
    
    public void setCell(String cell) {
        this.cell = cell;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="citizen")
    public Set<Complaint> getCOMPLAINT_CITIZENS() {
        return this.COMPLAINT_CITIZENS;
    }
    
    public void setCOMPLAINT_CITIZENS(Set<Complaint> COMPLAINT_CITIZENS) {
        this.COMPLAINT_CITIZENS = COMPLAINT_CITIZENS;
    }




}


