package za.co.egov.epart;
// Generated 19 Oct 2015 9:27:56 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComplaintHelp generated by hbm2java
 */
@Entity
@Table(name="complainthelp"
    ,schema="public"
)
public class ComplaintHelp  implements java.io.Serializable {


     private Integer id;
     private String key;
     private String comval;

    public ComplaintHelp() {
    }

    public ComplaintHelp(String key, String comval) {
       this.key = key;
       this.comval = comval;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="key", length=100)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    
    @Column(name="comval", length=100)
    public String getComval() {
        return this.comval;
    }
    
    public void setComval(String comval) {
        this.comval = comval;
    }




}


