package za.co.egov.epart;
// Generated 24 Oct 2015 4:19:38 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComplaintHelp generated by hbm2java
 */
@Entity
@Table(name="complainthelp"
    ,schema="public"
)
public class ComplaintHelp  implements java.io.Serializable {


     private Integer id;
     private String key;
     private String comval;
     private Agency agency;
     private ComplaintType complainttype;

    public ComplaintHelp() {
    }

	
    public ComplaintHelp(Agency agency) {
        this.agency = agency;
    }
    public ComplaintHelp(String key, String comval, Agency agency, ComplaintType complainttype) {
       this.key = key;
       this.comval = comval;
       this.agency = agency;
       this.complainttype = complainttype;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="key", length=100)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    
    @Column(name="comval", length=100)
    public String getComval() {
        return this.comval;
    }
    
    public void setComval(String comval) {
        this.comval = comval;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPLAINTHELP_AGENCY_ID", nullable=false)
    public Agency getAgency() {
        return this.agency;
    }
    
    public void setAgency(Agency agency) {
        this.agency = agency;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPLAINTHELP_COMPLAINTTYPE_ID")
    public ComplaintType getComplainttype() {
        return this.complainttype;
    }
    
    public void setComplainttype(ComplaintType complainttype) {
        this.complainttype = complainttype;
    }




}


