package za.co.egov.epart;
// Generated 18 Nov 2015 12:33:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,schema="public"
)
public class Department  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Province province;
     private Set<Agency> AGENCY_DEPARTMENTS = new HashSet<Agency>(0);

    public Department() {
    }

	
    public Department(Province province) {
        this.province = province;
    }
    public Department(String name, Province province, Set<Agency> AGENCY_DEPARTMENTS) {
       this.name = name;
       this.province = province;
       this.AGENCY_DEPARTMENTS = AGENCY_DEPARTMENTS;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEPARTMENT_PROVINCE_ID", nullable=false)
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="department")
    public Set<Agency> getAGENCY_DEPARTMENTS() {
        return this.AGENCY_DEPARTMENTS;
    }
    
    public void setAGENCY_DEPARTMENTS(Set<Agency> AGENCY_DEPARTMENTS) {
        this.AGENCY_DEPARTMENTS = AGENCY_DEPARTMENTS;
    }




}


