/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.egov;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EGovDslRuntimeModule extends com.dsleng.etool.dsl.egov.AbstractEGovDslRuntimeModule {

}
