/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.egov;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EGovDslStandaloneSetup extends EGovDslStandaloneSetupGenerated{

	public static void doSetup() {
		new EGovDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

