/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.dsleng.etool.dsl.bobjs


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BObjDslRuntimeModule extends AbstractBObjDslRuntimeModule {
}
