/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.bobjs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BObjDslUiModule extends com.dsleng.etool.dsl.bobjs.ui.AbstractBObjDslUiModule {
	public BObjDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
