/**
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.ui.contentassist;

import com.dsleng.etool.semantic.map.ui.contentassist.AbstractSemanticmapDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SemanticmapDslProposalProvider extends AbstractSemanticmapDslProposalProvider {
}
