/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ControlsUiModule extends com.dsleng.etool.dsl.ui.AbstractControlsUiModule {
	public ControlsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
