/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.egov.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EGovDslUiModule extends com.dsleng.etool.dsl.egov.ui.AbstractEGovDslUiModule {
	public EGovDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
