<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="com" nsURI="http://com/dsleng/etool/presentation/view" nsPrefix="com.dsleng.etool.presentation.view">
  <eSubpackages name="dsleng" nsURI="http://com/dsleng/" nsPrefix="com">
    <eSubpackages name="etool" nsURI="http://com/dsleng/etool/" nsPrefix="com.dsleng">
      <eSubpackages name="presentation" nsURI="http://com/dsleng/etool/presentation"
          nsPrefix="com.dsleng.etool">
        <eSubpackages name="view" nsURI="http://com/dsleng/etool/presentation/view/"
            nsPrefix="com.dsleng.etool.presentation">
          <eClassifiers xsi:type="ecore:EClass" name="Layout">
            <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
                eType="#//dsleng/etool/presentation/view/Layers" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Layers">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//dsleng/etool/presentation/view/LayoutPosition"
                defaultValueLiteral="center"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="resizable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Horizontal" eSuperTypes="#//dsleng/etool/presentation/view/Layers">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Vertical" eSuperTypes="#//dsleng/etool/presentation/view/Layers">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="LayoutPosition">
            <eLiterals name="center"/>
            <eLiterals name="west" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Content" eSuperTypes="#//dsleng/etool/presentation/view/Layers">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Page">
            <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
                eType="#//dsleng/etool/presentation/view/Layout" containment="true"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
