/**
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.validation;

import com.dsleng.etool.semantic.map.validation.AbstractSemanticmapDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SemanticmapDslValidator extends AbstractSemanticmapDslValidator {
}
