/**
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.serializer;

import com.dsleng.etool.semantic.map.serializer.AbstractSemanticmapDslSyntacticSequencer;

@SuppressWarnings("all")
public class SemanticmapDslSyntacticSequencer extends AbstractSemanticmapDslSyntacticSequencer {
}
