/**
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.serializer;

import com.dsleng.etool.semantic.map.serializer.AbstractSemanticmapDslSemanticSequencer;

@SuppressWarnings("all")
public class SemanticmapDslSemanticSequencer extends AbstractSemanticmapDslSemanticSequencer {
}
