/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.serializer;


class SemanticmapDslSyntacticSequencer extends AbstractSemanticmapDslSyntacticSequencer {
}
