/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ViewDslRuntimeModule extends com.dsleng.etool.xtext.presentation.view.AbstractViewDslRuntimeModule {

}
