/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ControlsRuntimeModule extends com.dsleng.etool.dsl.AbstractControlsRuntimeModule {

}
