/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ControlsStandaloneSetup extends ControlsStandaloneSetupGenerated{

	public static void doSetup() {
		new ControlsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

