/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import com.dsleng.etool.dsl.scoping.ControlsDslQNP;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ControlsRuntimeModule extends com.dsleng.etool.dsl.AbstractControlsRuntimeModule {
	
	@Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return ControlsDslQNP.class;
    }
}
