/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dsleng.etool.xtext.presentation.view.ui.internal.ViewDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ViewDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ViewDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ViewDslActivator.getInstance().getInjector(ViewDslActivator.COM_DSLENG_ETOOL_XTEXT_PRESENTATION_VIEW_VIEWDSL);
	}
	
}
