/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.view;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ViewDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.dsleng.etool.xtext.view.ui.internal.ViewDSLActivator.getInstance().getInjector("com.dsleng.etool.xtext.view.ViewDSL");
	}
	
}
