/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.view.ui.contentassist

import com.dsleng.etool.xtext.view.ui.contentassist.AbstractViewDSLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ViewDSLProposalProvider extends AbstractViewDSLProposalProvider {
}
