/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SemanticmapDslRuntimeModule extends com.dsleng.etool.semantic.map.AbstractSemanticmapDslRuntimeModule {

}
