package za.co.egov.cn;
// Generated 16 Oct 2015 3:55:56 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,schema="public"
)
public class Client  implements java.io.Serializable {


     private Integer id;
     private String IdNo;
     private String cardno;
     private String firstname1;
     private String firstname2;
     private String firstname3;
     private String surname;
     private String telphoneno;
     private String cellno;
     private String email;
     private String PrefContact;

    public Client() {
    }

    public Client(String IdNo, String cardno, String firstname1, String firstname2, String firstname3, String surname, String telphoneno, String cellno, String email, String PrefContact) {
       this.IdNo = IdNo;
       this.cardno = cardno;
       this.firstname1 = firstname1;
       this.firstname2 = firstname2;
       this.firstname3 = firstname3;
       this.surname = surname;
       this.telphoneno = telphoneno;
       this.cellno = cellno;
       this.email = email;
       this.PrefContact = PrefContact;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="idno", length=20)
    public String getIdNo() {
        return this.IdNo;
    }
    
    public void setIdNo(String IdNo) {
        this.IdNo = IdNo;
    }
    
    @Column(name="cardno", length=20)
    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    
    @Column(name="firstname1", length=20)
    public String getFirstname1() {
        return this.firstname1;
    }
    
    public void setFirstname1(String firstname1) {
        this.firstname1 = firstname1;
    }
    
    @Column(name="firstname2", length=20)
    public String getFirstname2() {
        return this.firstname2;
    }
    
    public void setFirstname2(String firstname2) {
        this.firstname2 = firstname2;
    }
    
    @Column(name="firstname3", length=20)
    public String getFirstname3() {
        return this.firstname3;
    }
    
    public void setFirstname3(String firstname3) {
        this.firstname3 = firstname3;
    }
    
    @Column(name="surname", length=20)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="telphoneno", length=20)
    public String getTelphoneno() {
        return this.telphoneno;
    }
    
    public void setTelphoneno(String telphoneno) {
        this.telphoneno = telphoneno;
    }
    
    @Column(name="cellno", length=20)
    public String getCellno() {
        return this.cellno;
    }
    
    public void setCellno(String cellno) {
        this.cellno = cellno;
    }
    
    @Column(name="email", length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="prefcontact", length=20)
    public String getPrefContact() {
        return this.PrefContact;
    }
    
    public void setPrefContact(String PrefContact) {
        this.PrefContact = PrefContact;
    }




}


