package za.co.egov.cn;
// Generated 16 Oct 2015 3:55:56 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermitHistory generated by hbm2java
 */
@Entity
@Table(name="permithistory"
    ,schema="public"
)
public class PermitHistory  implements java.io.Serializable {


     private Integer id;
     private Date DateChanged;
     private String ReferenceNo;
     private String PermitNo;
     private String PermitDescription;
     private String NotificationSend;
     private String ReasonForChge;

    public PermitHistory() {
    }

    public PermitHistory(Date DateChanged, String ReferenceNo, String PermitNo, String PermitDescription, String NotificationSend, String ReasonForChge) {
       this.DateChanged = DateChanged;
       this.ReferenceNo = ReferenceNo;
       this.PermitNo = PermitNo;
       this.PermitDescription = PermitDescription;
       this.NotificationSend = NotificationSend;
       this.ReasonForChge = ReasonForChge;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="datechanged", length=13)
    public Date getDateChanged() {
        return this.DateChanged;
    }
    
    public void setDateChanged(Date DateChanged) {
        this.DateChanged = DateChanged;
    }
    
    @Column(name="referenceno", length=20)
    public String getReferenceNo() {
        return this.ReferenceNo;
    }
    
    public void setReferenceNo(String ReferenceNo) {
        this.ReferenceNo = ReferenceNo;
    }
    
    @Column(name="permitno", length=20)
    public String getPermitNo() {
        return this.PermitNo;
    }
    
    public void setPermitNo(String PermitNo) {
        this.PermitNo = PermitNo;
    }
    
    @Column(name="permitdescription", length=20)
    public String getPermitDescription() {
        return this.PermitDescription;
    }
    
    public void setPermitDescription(String PermitDescription) {
        this.PermitDescription = PermitDescription;
    }
    
    @Column(name="notificationsend", length=20)
    public String getNotificationSend() {
        return this.NotificationSend;
    }
    
    public void setNotificationSend(String NotificationSend) {
        this.NotificationSend = NotificationSend;
    }
    
    @Column(name="reasonforchge", length=20)
    public String getReasonForChge() {
        return this.ReasonForChge;
    }
    
    public void setReasonForChge(String ReasonForChge) {
        this.ReasonForChge = ReasonForChge;
    }




}


