/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.bobjs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BObjDslRuntimeModule extends com.dsleng.etool.dsl.bobjs.AbstractBObjDslRuntimeModule {

}
