/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.ui.contentassist

import com.dsleng.etool.dsl.ui.contentassist.AbstractControlsProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ControlsProposalProvider extends AbstractControlsProposalProvider {
}
