<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="com" nsURI="http://com/dsleng/etool/presentation/view" nsPrefix="com.dsleng.etool.presentation.view">
  <eSubpackages name="dsleng" nsURI="http://com/dsleng/" nsPrefix="com">
    <eSubpackages name="etool" nsURI="http://com/dsleng/etool/" nsPrefix="com.dsleng">
      <eSubpackages name="models" nsURI="http://com/dsleng/etool/models" nsPrefix="com.dsleng.etool">
        <eSubpackages name="egov" nsURI="http://com/dsleng/etool/models/egov" nsPrefix="com.dsleng.etool.models">
          <eClassifiers xsi:type="ecore:EClass" name="EService" eSuperTypes="#//dsleng/etool/models/egov/NamedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
                eType="#//dsleng/etool/models/egov/Page" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="indexPage" lowerBound="1"
                eType="#//dsleng/etool/models/egov/Page"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BusinessObject" eSuperTypes="#//dsleng/etool/models/egov/NamedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
                eType="#//dsleng/etool/models/egov/Attribute" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
                eType="#//dsleng/etool/models/egov/References" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Dept" eSuperTypes="#//dsleng/etool/models/egov/NamedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="eservices" upperBound="-1"
                eType="#//dsleng/etool/models/egov/EService" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="businessobjects"
                upperBound="-1" eType="#//dsleng/etool/models/egov/BusinessObject"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//dsleng/etool/models/egov/NamedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="businessobject"
                lowerBound="1" eType="#//dsleng/etool/models/egov/BusinessObject"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="nextPage" eType="#//dsleng/etool/models/egov/Page"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//dsleng/etool/models/egov/NamedElement">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//dsleng/etool/models/egov/DataTypes"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
            <eLiterals name="Integer"/>
            <eLiterals name="String" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="References">
            <eStructuralFeatures xsi:type="ecore:EReference" name="businessobject"
                eType="#//dsleng/etool/models/egov/BusinessObject"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="Inclusion" eType="#//dsleng/etool/models/egov/Inclusions"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//dsleng/etool/models/egov/Multiplicity"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="Inclusions">
            <eLiterals name="Mandatory"/>
            <eLiterals name="Optional" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
            <eLiterals name="OnlyOne" literal="OnlyOne"/>
            <eLiterals name="Many" value="1"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
