/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ViewDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLayoutKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLayoutAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLayoutLayoutParserRuleCall_3_0 = (RuleCall)cLayoutAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		////import "platform:/resource/com.dsleng.etool.presentation/model/view.ecore" as view
		//Page returns view::Page:
		//	"Page" "{" "layout" layout=Layout "}";
		@Override public ParserRule getRule() { return rule; }

		//"Page" "{" "layout" layout=Layout "}"
		public Group getGroup() { return cGroup; }

		//"Page"
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"layout"
		public Keyword getLayoutKeyword_2() { return cLayoutKeyword_2; }

		//layout=Layout
		public Assignment getLayoutAssignment_3() { return cLayoutAssignment_3; }

		//Layout
		public RuleCall getLayoutLayoutParserRuleCall_3_0() { return cLayoutLayoutParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class LayersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Layers");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLayers_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cHorizontalParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVerticalParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cContentParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Layers returns view::Layers:
		//	Layers_Impl | Horizontal | Vertical | Content;
		@Override public ParserRule getRule() { return rule; }

		//Layers_Impl | Horizontal | Vertical | Content
		public Alternatives getAlternatives() { return cAlternatives; }

		//Layers_Impl
		public RuleCall getLayers_ImplParserRuleCall_0() { return cLayers_ImplParserRuleCall_0; }

		//Horizontal
		public RuleCall getHorizontalParserRuleCall_1() { return cHorizontalParserRuleCall_1; }

		//Vertical
		public RuleCall getVerticalParserRuleCall_2() { return cVerticalParserRuleCall_2; }

		//Content
		public RuleCall getContentParserRuleCall_3() { return cContentParserRuleCall_3; }
	}

	public class LayoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Layout");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLayoutAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLayoutKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLayersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cLayersAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cLayersLayersParserRuleCall_3_2_0 = (RuleCall)cLayersAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cLayersAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cLayersLayersParserRuleCall_3_3_1_0 = (RuleCall)cLayersAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Layout returns view::Layout:
		//	{view::Layout} "Layout" "{" ("layers" "{" layers+=Layers ("," layers+=Layers)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{view::Layout} "Layout" "{" ("layers" "{" layers+=Layers ("," layers+=Layers)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{view::Layout}
		public Action getLayoutAction_0() { return cLayoutAction_0; }

		//"Layout"
		public Keyword getLayoutKeyword_1() { return cLayoutKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("layers" "{" layers+=Layers ("," layers+=Layers)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"layers"
		public Keyword getLayersKeyword_3_0() { return cLayersKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//layers+=Layers
		public Assignment getLayersAssignment_3_2() { return cLayersAssignment_3_2; }

		//Layers
		public RuleCall getLayersLayersParserRuleCall_3_2_0() { return cLayersLayersParserRuleCall_3_2_0; }

		//("," layers+=Layers)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//layers+=Layers
		public Assignment getLayersAssignment_3_3_1() { return cLayersAssignment_3_3_1; }

		//Layers
		public RuleCall getLayersLayersParserRuleCall_3_3_1_0() { return cLayersLayersParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class Layers_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Layers_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLayersAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cResizableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cResizableResizableKeyword_1_0 = (Keyword)cResizableAssignment_1.eContents().get(0);
		private final Keyword cLayersKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStyleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStyleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStyleEStringParserRuleCall_4_1_0 = (RuleCall)cStyleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPositionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPositionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPositionLayoutPositionEnumRuleCall_5_1_0 = (RuleCall)cPositionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMinSizeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMinSizeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMinSizeEIntParserRuleCall_6_1_0 = (RuleCall)cMinSizeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaxSizeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaxSizeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaxSizeEIntParserRuleCall_7_1_0 = (RuleCall)cMaxSizeAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Layers_Impl returns view::Layers:
		//	{view::Layers} resizable?="resizable"? "Layers" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{view::Layers} resizable?="resizable"? "Layers" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{view::Layers}
		public Action getLayersAction_0() { return cLayersAction_0; }

		//resizable?="resizable"?
		public Assignment getResizableAssignment_1() { return cResizableAssignment_1; }

		//"resizable"
		public Keyword getResizableResizableKeyword_1_0() { return cResizableResizableKeyword_1_0; }

		//"Layers"
		public Keyword getLayersKeyword_2() { return cLayersKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("style" style=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"style"
		public Keyword getStyleKeyword_4_0() { return cStyleKeyword_4_0; }

		//style=EString
		public Assignment getStyleAssignment_4_1() { return cStyleAssignment_4_1; }

		//EString
		public RuleCall getStyleEStringParserRuleCall_4_1_0() { return cStyleEStringParserRuleCall_4_1_0; }

		//("position" position=LayoutPosition)?
		public Group getGroup_5() { return cGroup_5; }

		//"position"
		public Keyword getPositionKeyword_5_0() { return cPositionKeyword_5_0; }

		//position=LayoutPosition
		public Assignment getPositionAssignment_5_1() { return cPositionAssignment_5_1; }

		//LayoutPosition
		public RuleCall getPositionLayoutPositionEnumRuleCall_5_1_0() { return cPositionLayoutPositionEnumRuleCall_5_1_0; }

		//("minSize" minSize=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"minSize"
		public Keyword getMinSizeKeyword_6_0() { return cMinSizeKeyword_6_0; }

		//minSize=EInt
		public Assignment getMinSizeAssignment_6_1() { return cMinSizeAssignment_6_1; }

		//EInt
		public RuleCall getMinSizeEIntParserRuleCall_6_1_0() { return cMinSizeEIntParserRuleCall_6_1_0; }

		//("maxSize" maxSize=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"maxSize"
		public Keyword getMaxSizeKeyword_7_0() { return cMaxSizeKeyword_7_0; }

		//maxSize=EInt
		public Assignment getMaxSizeAssignment_7_1() { return cMaxSizeAssignment_7_1; }

		//EInt
		public RuleCall getMaxSizeEIntParserRuleCall_7_1_0() { return cMaxSizeEIntParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		@Override public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class HorizontalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Horizontal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHorizontalAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cResizableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cResizableResizableKeyword_1_0 = (Keyword)cResizableAssignment_1.eContents().get(0);
		private final Keyword cHorizontalKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStyleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStyleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStyleEStringParserRuleCall_4_1_0 = (RuleCall)cStyleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPositionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPositionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPositionLayoutPositionEnumRuleCall_5_1_0 = (RuleCall)cPositionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMinSizeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMinSizeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMinSizeEIntParserRuleCall_6_1_0 = (RuleCall)cMinSizeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaxSizeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaxSizeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaxSizeEIntParserRuleCall_7_1_0 = (RuleCall)cMaxSizeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cHeightKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHeightAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cHeightEIntParserRuleCall_8_1_0 = (RuleCall)cHeightAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Horizontal returns view::Horizontal:
		//	{view::Horizontal} resizable?="resizable"? "Horizontal" "{" ("style" style=EString)? ("position"
		//	position=LayoutPosition)? ("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{view::Horizontal} resizable?="resizable"? "Horizontal" "{" ("style" style=EString)? ("position"
		//position=LayoutPosition)? ("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{view::Horizontal}
		public Action getHorizontalAction_0() { return cHorizontalAction_0; }

		//resizable?="resizable"?
		public Assignment getResizableAssignment_1() { return cResizableAssignment_1; }

		//"resizable"
		public Keyword getResizableResizableKeyword_1_0() { return cResizableResizableKeyword_1_0; }

		//"Horizontal"
		public Keyword getHorizontalKeyword_2() { return cHorizontalKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("style" style=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"style"
		public Keyword getStyleKeyword_4_0() { return cStyleKeyword_4_0; }

		//style=EString
		public Assignment getStyleAssignment_4_1() { return cStyleAssignment_4_1; }

		//EString
		public RuleCall getStyleEStringParserRuleCall_4_1_0() { return cStyleEStringParserRuleCall_4_1_0; }

		//("position" position=LayoutPosition)?
		public Group getGroup_5() { return cGroup_5; }

		//"position"
		public Keyword getPositionKeyword_5_0() { return cPositionKeyword_5_0; }

		//position=LayoutPosition
		public Assignment getPositionAssignment_5_1() { return cPositionAssignment_5_1; }

		//LayoutPosition
		public RuleCall getPositionLayoutPositionEnumRuleCall_5_1_0() { return cPositionLayoutPositionEnumRuleCall_5_1_0; }

		//("minSize" minSize=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"minSize"
		public Keyword getMinSizeKeyword_6_0() { return cMinSizeKeyword_6_0; }

		//minSize=EInt
		public Assignment getMinSizeAssignment_6_1() { return cMinSizeAssignment_6_1; }

		//EInt
		public RuleCall getMinSizeEIntParserRuleCall_6_1_0() { return cMinSizeEIntParserRuleCall_6_1_0; }

		//("maxSize" maxSize=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"maxSize"
		public Keyword getMaxSizeKeyword_7_0() { return cMaxSizeKeyword_7_0; }

		//maxSize=EInt
		public Assignment getMaxSizeAssignment_7_1() { return cMaxSizeAssignment_7_1; }

		//EInt
		public RuleCall getMaxSizeEIntParserRuleCall_7_1_0() { return cMaxSizeEIntParserRuleCall_7_1_0; }

		//("height" height=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"height"
		public Keyword getHeightKeyword_8_0() { return cHeightKeyword_8_0; }

		//height=EInt
		public Assignment getHeightAssignment_8_1() { return cHeightAssignment_8_1; }

		//EInt
		public RuleCall getHeightEIntParserRuleCall_8_1_0() { return cHeightEIntParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class VerticalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Vertical");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVerticalAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cResizableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cResizableResizableKeyword_1_0 = (Keyword)cResizableAssignment_1.eContents().get(0);
		private final Keyword cVerticalKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStyleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStyleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStyleEStringParserRuleCall_4_1_0 = (RuleCall)cStyleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPositionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPositionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPositionLayoutPositionEnumRuleCall_5_1_0 = (RuleCall)cPositionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMinSizeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMinSizeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMinSizeEIntParserRuleCall_6_1_0 = (RuleCall)cMinSizeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaxSizeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaxSizeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaxSizeEIntParserRuleCall_7_1_0 = (RuleCall)cMaxSizeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cWidthKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cWidthAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_8_1_0 = (RuleCall)cWidthAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Vertical returns view::Vertical:
		//	{view::Vertical} resizable?="resizable"? "Vertical" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("width" width=EInt)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{view::Vertical} resizable?="resizable"? "Vertical" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("width" width=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{view::Vertical}
		public Action getVerticalAction_0() { return cVerticalAction_0; }

		//resizable?="resizable"?
		public Assignment getResizableAssignment_1() { return cResizableAssignment_1; }

		//"resizable"
		public Keyword getResizableResizableKeyword_1_0() { return cResizableResizableKeyword_1_0; }

		//"Vertical"
		public Keyword getVerticalKeyword_2() { return cVerticalKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("style" style=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"style"
		public Keyword getStyleKeyword_4_0() { return cStyleKeyword_4_0; }

		//style=EString
		public Assignment getStyleAssignment_4_1() { return cStyleAssignment_4_1; }

		//EString
		public RuleCall getStyleEStringParserRuleCall_4_1_0() { return cStyleEStringParserRuleCall_4_1_0; }

		//("position" position=LayoutPosition)?
		public Group getGroup_5() { return cGroup_5; }

		//"position"
		public Keyword getPositionKeyword_5_0() { return cPositionKeyword_5_0; }

		//position=LayoutPosition
		public Assignment getPositionAssignment_5_1() { return cPositionAssignment_5_1; }

		//LayoutPosition
		public RuleCall getPositionLayoutPositionEnumRuleCall_5_1_0() { return cPositionLayoutPositionEnumRuleCall_5_1_0; }

		//("minSize" minSize=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"minSize"
		public Keyword getMinSizeKeyword_6_0() { return cMinSizeKeyword_6_0; }

		//minSize=EInt
		public Assignment getMinSizeAssignment_6_1() { return cMinSizeAssignment_6_1; }

		//EInt
		public RuleCall getMinSizeEIntParserRuleCall_6_1_0() { return cMinSizeEIntParserRuleCall_6_1_0; }

		//("maxSize" maxSize=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"maxSize"
		public Keyword getMaxSizeKeyword_7_0() { return cMaxSizeKeyword_7_0; }

		//maxSize=EInt
		public Assignment getMaxSizeAssignment_7_1() { return cMaxSizeAssignment_7_1; }

		//EInt
		public RuleCall getMaxSizeEIntParserRuleCall_7_1_0() { return cMaxSizeEIntParserRuleCall_7_1_0; }

		//("width" width=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"width"
		public Keyword getWidthKeyword_8_0() { return cWidthKeyword_8_0; }

		//width=EInt
		public Assignment getWidthAssignment_8_1() { return cWidthAssignment_8_1; }

		//EInt
		public RuleCall getWidthEIntParserRuleCall_8_1_0() { return cWidthEIntParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class ContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Content");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cContentAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cResizableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cResizableResizableKeyword_1_0 = (Keyword)cResizableAssignment_1.eContents().get(0);
		private final Keyword cContentKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStyleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStyleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStyleEStringParserRuleCall_4_1_0 = (RuleCall)cStyleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPositionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPositionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPositionLayoutPositionEnumRuleCall_5_1_0 = (RuleCall)cPositionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMinSizeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMinSizeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMinSizeEIntParserRuleCall_6_1_0 = (RuleCall)cMinSizeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaxSizeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaxSizeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaxSizeEIntParserRuleCall_7_1_0 = (RuleCall)cMaxSizeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cHeightKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHeightAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cHeightEIntParserRuleCall_8_1_0 = (RuleCall)cHeightAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cWidthKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cWidthAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_9_1_0 = (RuleCall)cWidthAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Content returns view::Content:
		//	{view::Content} resizable?="resizable"? "Content" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? ("width" width=EInt)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{view::Content} resizable?="resizable"? "Content" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
		//("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? ("width" width=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{view::Content}
		public Action getContentAction_0() { return cContentAction_0; }

		//resizable?="resizable"?
		public Assignment getResizableAssignment_1() { return cResizableAssignment_1; }

		//"resizable"
		public Keyword getResizableResizableKeyword_1_0() { return cResizableResizableKeyword_1_0; }

		//"Content"
		public Keyword getContentKeyword_2() { return cContentKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("style" style=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"style"
		public Keyword getStyleKeyword_4_0() { return cStyleKeyword_4_0; }

		//style=EString
		public Assignment getStyleAssignment_4_1() { return cStyleAssignment_4_1; }

		//EString
		public RuleCall getStyleEStringParserRuleCall_4_1_0() { return cStyleEStringParserRuleCall_4_1_0; }

		//("position" position=LayoutPosition)?
		public Group getGroup_5() { return cGroup_5; }

		//"position"
		public Keyword getPositionKeyword_5_0() { return cPositionKeyword_5_0; }

		//position=LayoutPosition
		public Assignment getPositionAssignment_5_1() { return cPositionAssignment_5_1; }

		//LayoutPosition
		public RuleCall getPositionLayoutPositionEnumRuleCall_5_1_0() { return cPositionLayoutPositionEnumRuleCall_5_1_0; }

		//("minSize" minSize=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"minSize"
		public Keyword getMinSizeKeyword_6_0() { return cMinSizeKeyword_6_0; }

		//minSize=EInt
		public Assignment getMinSizeAssignment_6_1() { return cMinSizeAssignment_6_1; }

		//EInt
		public RuleCall getMinSizeEIntParserRuleCall_6_1_0() { return cMinSizeEIntParserRuleCall_6_1_0; }

		//("maxSize" maxSize=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"maxSize"
		public Keyword getMaxSizeKeyword_7_0() { return cMaxSizeKeyword_7_0; }

		//maxSize=EInt
		public Assignment getMaxSizeAssignment_7_1() { return cMaxSizeAssignment_7_1; }

		//EInt
		public RuleCall getMaxSizeEIntParserRuleCall_7_1_0() { return cMaxSizeEIntParserRuleCall_7_1_0; }

		//("height" height=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"height"
		public Keyword getHeightKeyword_8_0() { return cHeightKeyword_8_0; }

		//height=EInt
		public Assignment getHeightAssignment_8_1() { return cHeightAssignment_8_1; }

		//EInt
		public RuleCall getHeightEIntParserRuleCall_8_1_0() { return cHeightEIntParserRuleCall_8_1_0; }

		//("width" width=EInt)?
		public Group getGroup_9() { return cGroup_9; }

		//"width"
		public Keyword getWidthKeyword_9_0() { return cWidthKeyword_9_0; }

		//width=EInt
		public Assignment getWidthAssignment_9_1() { return cWidthAssignment_9_1; }

		//EInt
		public RuleCall getWidthEIntParserRuleCall_9_1_0() { return cWidthEIntParserRuleCall_9_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	
	
	public class LayoutPositionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "LayoutPosition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCenterEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCenterCenterKeyword_0_0 = (Keyword)cCenterEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWestEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWestWestKeyword_1_0 = (Keyword)cWestEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum LayoutPosition returns view::LayoutPosition:
		//	center | west;
		public EnumRule getRule() { return rule; }

		//center | west
		public Alternatives getAlternatives() { return cAlternatives; }

		//center
		public EnumLiteralDeclaration getCenterEnumLiteralDeclaration_0() { return cCenterEnumLiteralDeclaration_0; }

		//"center"
		public Keyword getCenterCenterKeyword_0_0() { return cCenterCenterKeyword_0_0; }

		//west
		public EnumLiteralDeclaration getWestEnumLiteralDeclaration_1() { return cWestEnumLiteralDeclaration_1; }

		//"west"
		public Keyword getWestWestKeyword_1_0() { return cWestWestKeyword_1_0; }
	}
	
	private final PageElements pPage;
	private final LayersElements pLayers;
	private final LayoutElements pLayout;
	private final Layers_ImplElements pLayers_Impl;
	private final EStringElements pEString;
	private final LayoutPositionElements unknownRuleLayoutPosition;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final HorizontalElements pHorizontal;
	private final VerticalElements pVertical;
	private final ContentElements pContent;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ViewDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPage = new PageElements();
		this.pLayers = new LayersElements();
		this.pLayout = new LayoutElements();
		this.pLayers_Impl = new Layers_ImplElements();
		this.pEString = new EStringElements();
		this.unknownRuleLayoutPosition = new LayoutPositionElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pHorizontal = new HorizontalElements();
		this.pVertical = new VerticalElements();
		this.pContent = new ContentElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.dsleng.etool.xtext.presentation.view.ViewDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////import "platform:/resource/com.dsleng.etool.presentation/model/view.ecore" as view
	//Page returns view::Page:
	//	"Page" "{" "layout" layout=Layout "}";
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//Layers returns view::Layers:
	//	Layers_Impl | Horizontal | Vertical | Content;
	public LayersElements getLayersAccess() {
		return pLayers;
	}
	
	public ParserRule getLayersRule() {
		return getLayersAccess().getRule();
	}

	//Layout returns view::Layout:
	//	{view::Layout} "Layout" "{" ("layers" "{" layers+=Layers ("," layers+=Layers)* "}")? "}";
	public LayoutElements getLayoutAccess() {
		return pLayout;
	}
	
	public ParserRule getLayoutRule() {
		return getLayoutAccess().getRule();
	}

	//Layers_Impl returns view::Layers:
	//	{view::Layers} resizable?="resizable"? "Layers" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
	//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? "}";
	public Layers_ImplElements getLayers_ImplAccess() {
		return pLayers_Impl;
	}
	
	public ParserRule getLayers_ImplRule() {
		return getLayers_ImplAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//enum LayoutPosition returns view::LayoutPosition:
	//	center | west;
	public LayoutPositionElements getLayoutPositionAccess() {
		return unknownRuleLayoutPosition;
	}
	
	public EnumRule getLayoutPositionRule() {
		return getLayoutPositionAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//Horizontal returns view::Horizontal:
	//	{view::Horizontal} resizable?="resizable"? "Horizontal" "{" ("style" style=EString)? ("position"
	//	position=LayoutPosition)? ("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? "}";
	public HorizontalElements getHorizontalAccess() {
		return pHorizontal;
	}
	
	public ParserRule getHorizontalRule() {
		return getHorizontalAccess().getRule();
	}

	//Vertical returns view::Vertical:
	//	{view::Vertical} resizable?="resizable"? "Vertical" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
	//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("width" width=EInt)? "}";
	public VerticalElements getVerticalAccess() {
		return pVertical;
	}
	
	public ParserRule getVerticalRule() {
		return getVerticalAccess().getRule();
	}

	//Content returns view::Content:
	//	{view::Content} resizable?="resizable"? "Content" "{" ("style" style=EString)? ("position" position=LayoutPosition)?
	//	("minSize" minSize=EInt)? ("maxSize" maxSize=EInt)? ("height" height=EInt)? ("width" width=EInt)? "}";
	public ContentElements getContentAccess() {
		return pContent;
	}
	
	public ParserRule getContentRule() {
		return getContentAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
