/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.dsleng.etool.dsl.bobjs.validation

import org.eclipse.xtext.validation.Check
import com.dsleng.etool.model.bobjs.BusinessType
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EStructuralFeature
import com.dsleng.etool.model.bobjs.Attribute

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class BObjDslValidator extends AbstractBObjDslValidator {
	
	//@Check
	//def checkBusinessType(Attribute b){
	//	var p = 0
	//}
	
//	public static val INVALID_NAME = 'invalidName'
//
	//@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					BObjDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
