/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dsleng.etool.semantic.map.ui.internal.SemanticmapDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SemanticmapDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SemanticmapDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SemanticmapDslActivator.getInstance().getInjector(SemanticmapDslActivator.COM_DSLENG_ETOOL_SEMANTIC_MAP_SEMANTICMAPDSL);
	}
	
}
