/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.dsleng.etool.semantic.map.services.SemanticmapDslGrammarAccess;

public class SemanticmapDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SemanticmapDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.dsleng.etool.semantic.map.parser.antlr.internal.InternalSemanticmapDslParser createParser(XtextTokenStream stream) {
		return new com.dsleng.etool.semantic.map.parser.antlr.internal.InternalSemanticmapDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SemanticMapping";
	}
	
	public SemanticmapDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SemanticmapDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
