/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SemanticmapDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/dsleng/etool/semantic/map/parser/antlr/internal/InternalSemanticmapDsl.tokens");
	}
}
