/*
 * generated by Xtext
 */
package com.dsleng.etool.semantic.map.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SemanticmapDslUiModule extends com.dsleng.etool.semantic.map.ui.AbstractSemanticmapDslUiModule {
	public SemanticmapDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
