/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.view.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.dsleng.etool.xtext.view.services.ViewDSLGrammarAccess;

public class ViewDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private ViewDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.dsleng.etool.xtext.view.ui.contentassist.antlr.internal.InternalViewDSLParser createParser() {
		com.dsleng.etool.xtext.view.ui.contentassist.antlr.internal.InternalViewDSLParser result = new com.dsleng.etool.xtext.view.ui.contentassist.antlr.internal.InternalViewDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbilityAccess().getAlternatives(), "rule__Ability__Alternatives");
					put(grammarAccess.getSuperHeroAccess().getGroup(), "rule__SuperHero__Group__0");
					put(grammarAccess.getHerosAccess().getHerosAssignment(), "rule__Heros__HerosAssignment");
					put(grammarAccess.getSuperHeroAccess().getNameAssignment_1(), "rule__SuperHero__NameAssignment_1");
					put(grammarAccess.getSuperHeroAccess().getAbilitiesAssignment_3(), "rule__SuperHero__AbilitiesAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.dsleng.etool.xtext.view.ui.contentassist.antlr.internal.InternalViewDSLParser typedParser = (com.dsleng.etool.xtext.view.ui.contentassist.antlr.internal.InternalViewDSLParser) parser;
			typedParser.entryRuleHeros();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ViewDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ViewDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
