/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.dsleng.etool.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ControlsStandaloneSetup extends ControlsStandaloneSetupGenerated {

	def static void doSetup() {
		new ControlsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
