/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.dsleng.etool.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ControlsRuntimeModule extends AbstractControlsRuntimeModule {
}
