/*
 * generated by Xtext
 */
package com.dsleng.etool.dsl.egov.ui.contentassist

import com.dsleng.etool.dsl.egov.ui.contentassist.AbstractEGovDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class EGovDslProposalProvider extends AbstractEGovDslProposalProvider {
}
