/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.dsleng.etool.dsl.egov


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EGovStandaloneSetup extends EGovStandaloneSetupGenerated {

	def static void doSetup() {
		new EGovStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
