/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ViewDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/dsleng/etool/xtext/presentation/view/parser/antlr/internal/InternalViewDsl.tokens");
	}
}
