/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.dsleng.etool.xtext.presentation.view.services.ViewDslGrammarAccess;

public class ViewDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ViewDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.dsleng.etool.xtext.presentation.view.parser.antlr.internal.InternalViewDslParser createParser(XtextTokenStream stream) {
		return new com.dsleng.etool.xtext.presentation.view.parser.antlr.internal.InternalViewDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Page";
	}
	
	public ViewDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ViewDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
