/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.view.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dsleng.etool.xtext.view.ui.internal.ViewDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ViewDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ViewDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ViewDSLActivator.getInstance().getInjector(ViewDSLActivator.COM_DSLENG_ETOOL_XTEXT_VIEW_VIEWDSL);
	}
	
}
