/*
 * generated by Xtext
 */
package com.dsleng.etool.xtext.presentation.view.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ViewDslUiModule extends com.dsleng.etool.xtext.presentation.view.ui.AbstractViewDslUiModule {
	public ViewDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
