package za.co.egov.cn;
// Generated 19 Oct 2015 3:51:39 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PermitStatus generated by hbm2java
 */
@Entity
@Table(name="permitstatus"
    ,schema="public"
)
public class PermitStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set<Permit> PERMIT_PERMITSTATUSS = new HashSet<Permit>(0);
     private Set<PermitHistory> PERMITHISTORY_PERMITSTATUSS = new HashSet<PermitHistory>(0);

    public PermitStatus() {
    }

    public PermitStatus(String status, Set<Permit> PERMIT_PERMITSTATUSS, Set<PermitHistory> PERMITHISTORY_PERMITSTATUSS) {
       this.status = status;
       this.PERMIT_PERMITSTATUSS = PERMIT_PERMITSTATUSS;
       this.PERMITHISTORY_PERMITSTATUSS = PERMITHISTORY_PERMITSTATUSS;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="permitstatus")
    public Set<Permit> getPERMIT_PERMITSTATUSS() {
        return this.PERMIT_PERMITSTATUSS;
    }
    
    public void setPERMIT_PERMITSTATUSS(Set<Permit> PERMIT_PERMITSTATUSS) {
        this.PERMIT_PERMITSTATUSS = PERMIT_PERMITSTATUSS;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="permitstatus")
    public Set<PermitHistory> getPERMITHISTORY_PERMITSTATUSS() {
        return this.PERMITHISTORY_PERMITSTATUSS;
    }
    
    public void setPERMITHISTORY_PERMITSTATUSS(Set<PermitHistory> PERMITHISTORY_PERMITSTATUSS) {
        this.PERMITHISTORY_PERMITSTATUSS = PERMITHISTORY_PERMITSTATUSS;
    }




}


